# Heroku deployment configuratie voor AutoGen Marketing Team

setup:
  addons:
    - plan: heroku-postgresql:standard-0
      as: DATABASE
    - plan: cloudmqtt:cat
      as: RABBITMQ

build:
  docker:
    web: deployment/Dockerfile
    worker: deployment/Dockerfile.worker

release:
  command:
    - python src/db/migrations.py
  image: web

run:
  web: gunicorn src.web.wsgi --workers 4 --log-file -
  worker: python src/worker.py
  mcp_server: python src/mcp/server.py
  agent_manager: python src/agents/manager.py

config:
  ENVIRONMENT: production
  PYTHONUNBUFFERED: 1
  WEB_CONCURRENCY: 4
  AUTOGEN_DEBUG: false
  AI_PROVIDER: claude
  AI_MODEL: claude-3-5-sonnet
  ENABLE_MCP: true